# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The IT alrogirhm from Ulrich & Gotelli (2010)
#'
#' This function does blah blah blah.
#'
IT <- function(rowsums, colsums, nrow, ncol, N) {
    .Call('_spasm_IT', PACKAGE = 'spasm', rowsums, colsums, nrow, ncol, N)
}

